
version: '3.9'
services:
    
  db:
     image: postgres:latest
     restart: always
     environment:
      - POSTGRES_USER=Teo
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=CV-Backend

     ports:
       - '5432:5432'

